name: Python application

env:
  mimikko_data: ${{ secrets.MIMIKKO_DATA }}
  servant: ${{ secrets.SERVANT }}

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 准备python
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: 签到
      run: python test.py
